Repository WithAllMyAnimal/KittyAndPuppy, pull requests merged in 2023-11, with the labels that each got.

#125 [FIX, FEAT] 홈 피드 스피너 검색 기능 추가
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/DogAndCatAddActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/firebase/FBRef.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/Models.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageDaily.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
  app/src/main/res/layout/activity_dog_and_cat_add.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/spinnerItem.xml
Labels: Feature⚙️, Fix🔧

#127 [FEAT] 마이페이지 태그 필터 기능 구현
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/Models.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageDaily.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
Labels: Feature⚙️

#129 [FEAT] 반려동물의 생일이 되었을 때 케이크 아이콘 띄우기
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/DogAndCatAddActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/DialogProfileChange.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/res/layout/activity_detail_hospital.xml
  app/src/main/res/layout/activity_dog_and_cat_add.xml
  app/src/main/res/layout/fragment_dialog_profilechange.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/values/themes.xml
Labels: Feature⚙️

#130 [FEAT] 다른 유저가 보는 마이페이지 구현
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageOtherUsers.kt
  app/src/main/res/layout/activity_mypage_other_users.xml
Labels: Feature⚙️

#132 [DESIGN] : 🎨(UI추가): fragment_resign_dialog.xml추가,fragment_resignation…
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/ResignDialogFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/ResignationFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/setting/SettingActivity.kt
  app/src/main/res/layout/fragment_resign_dialog.xml
  app/src/main/res/layout/fragment_resignation.xml
  app/src/main/res/menu/menu_resignation.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values-w1240dp/dimens.xml
  app/src/main/res/values-w600dp/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Design🎨, Feature⚙️

#134 [FEAT] 홈피드 - 태그 검색 구현 중
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/Models.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageDaily.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
Labels: Feature⚙️, Fix🔧

#135 [FEAT] 홈피드 - 검색 기능 구현 완료
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/Models.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageDaily.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
Labels: Feature⚙️

#137 [FEAT] 좋아요 게시물 완성/ 가격 작성시 천단위마다 콤마
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/FindPwFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/FindPwGuideFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/firebase/FBRef.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
  app/src/main/res/layout/activity_mypage_pet.xml
  app/src/main/res/layout/fragment_find_pw_guide.xml
Labels: Feature⚙️

#138 [DESIGN] : 회원탈퇴 UI수정, 탈퇴하기 버튼 비활성화, 활성화 수정
  app/src/main/res/drawable/btn_disable_background.xml
  app/src/main/res/layout/fragment_resignation.xml
Labels: Design🎨, Feature⚙️

#140 [Feature]/likepage
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/firebase/FBRef.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
Labels: BugFix🐞

#141 [FIX] 좋아요 누른 게시물리스트에 내가 쓴 게시물까지 보이는 현상 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
Labels: BugFix🐞

#142 [FEAT] : ⚙️(댓글삭제기능): 댓글삭제기능 다 지워지는거 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsModel.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/res/layout/item_comments.xml
Labels: BugFix🐞, Feature⚙️

#143 [FEAT] 일지 수정 기능
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/firebase/util.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageOtherUsers.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/Models.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageDaily.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
  app/src/main/res/drawable/image_savebtn.xml
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/layout/activity_detail_daily.xml
  app/src/main/res/layout/activity_mypage_behavior.xml
  app/src/main/res/layout/activity_mypage_other_users.xml
  app/src/main/res/layout/fragment_dialog_profilechange.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/values/spinnerItem.xml
Labels: Feature⚙️, Fix🔧

#145 [Design] 전반적인 UI 수정을 하였습니다.
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/FindPwFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/FindPwGuideFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/firebase/util.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/setting/SettingLogoutFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageDaily.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
  app/src/main/res/drawable/tag_background_white.xml
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/layout/activity_detail_daily.xml
  app/src/main/res/layout/activity_detail_hospital.xml
  app/src/main/res/layout/activity_detail_pet.xml
  app/src/main/res/layout/activity_dog_and_cat_add.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/fab_layout.xml
  app/src/main/res/layout/fragment_comments.xml
  app/src/main/res/layout/fragment_dialog_profilechange.xml
  app/src/main/res/layout/fragment_find_pw.xml
  app/src/main/res/layout/fragment_find_pw_guide.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_login_add_item.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_resignation.xml
  app/src/main/res/layout/fragment_setting_logout.xml
  app/src/main/res/layout/fragment_setting_passworddialog.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/layout/item_mypage_like_list.xml
  app/src/main/res/layout/item_mypage_list.xml
  app/src/main/res/menu/main_menu.xml
Labels: Design🎨

#146 [Design] 전반적인 UI 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/DogAndCatAddActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/DialogProfileChange.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageOtherUsers.kt
  app/src/main/res/drawable/iv_mypage_birthday.xml
  app/src/main/res/drawable/mypage_birthday_crown.png
  app/src/main/res/layout/activity_mypage_hospital.xml
  app/src/main/res/layout/activity_mypage_other_users.xml
  app/src/main/res/layout/activity_mypage_pet.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/item_mypage_like_list.xml
  app/src/main/res/values/style.xml
Labels: Design🎨

#147 [FEAT] 일지 이미지 수정 시 홈 피드 바로 반영
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MainActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/SplashActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/firebase/util.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeViewModel.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/Models.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageDaily.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
  app/src/main/res/values/spinnerItem.xml
Labels: BugFix🐞, Feature⚙️

#149 [Feature]/likepage
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageDaily.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
Labels: Fix🔧

#150 [Fix] 이미지 db에 올리는 경로 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/firebase/util.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeViewModel.kt
Labels: BugFix🐞

#151 [FIX] 게시글 삭제 시 댓글, 좋아요 db도 삭제
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/setting/SettingPasswordDialogFragment.kt
  app/src/main/res/layout/fragment_setting_passworddialog.xml
Labels: BugFix🐞

#152 [feature]/Dialogprofile
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/DialogProfileChange.kt
Labels: Fix🔧

#154 [FIX] : 마이페이지 이미지 수정 바로 반영
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MainActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsFragment.kt
Labels: Fix🔧

#155 [FEAT] 삭제된 태그가 보이는 오류 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MainActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageDaily.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
  app/src/main/res/layout/activity_dog_and_cat_add.xml
  app/src/main/res/layout/item_home.xml
Labels: Fix🔧

#156 [BUGFIX] 홈피드 이미지 에러 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/firebase/util.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeViewModel.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/setting/ResignDialogFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/setting/ResignationFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/setting/SettingActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/Models.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageDaily.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
Labels: BugFix🐞

#157 [FIX] TAG 오류 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageDaily.kt
  app/src/main/res/layout/item_home.xml
Labels: BugFix🐞, Fix🔧

#158 [FIX] TAG 오류 수정 (Hospital, Pet, Behavior)
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
Labels: BugFix🐞

#159 [BUG FIX] 버그!!!!!!!!!!!!!!!!!!!!!!
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/firebase/util.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeViewModel.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/Models.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageDaily.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
Labels: BugFix🐞

#161 [FIX] : 마이페이지 이미지 수정 바로 반영
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageOtherUsers.kt
Labels: Fix🔧

#162 [Feature]/homerefresh
  app/build.gradle.kts
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
  app/src/main/res/layout/fragment_home.xml
Labels: Feature⚙️

#163 [BUGFIX] 게시글 삭제 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/Models.kt
Labels: BugFix🐞

#164 [BUGFIX] 이미지 변경 시 상세페이지 바로 적용
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageOtherUsers.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
Labels: BugFix🐞

#166 [Feature]/homerefresh
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
Labels: Feature⚙️, Fix🔧

#167 [Design FIX] Swiperfreshlayout 위치 오류 수정
  app/src/main/res/layout/fragment_home.xml
Labels: Design🎨

#168 [BUGFIX] 게시글 수정 시 내용 즉각 반영
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageDaily.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
Labels: Fix🔧

#169 [Design] 일부 UI 수정 (일지, 피드, 다이얼로그)
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/layout/activity_detail_daily.xml
  app/src/main/res/layout/activity_detail_hospital.xml
  app/src/main/res/layout/activity_detail_pet.xml
  app/src/main/res/layout/activity_dog_and_cat_add.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_resignation.xml
Labels: Design🎨

#170 [FEAT] 스피너는 새로고침안되고 선택사항이 변동되지않게 기능을 추가
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
Labels: Feature⚙️

#171 [FIX] 마이피드 addvalueeventlistener 제거
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageOtherUsers.kt
Labels: Fix🔧

#172 [FIX] : 마이페이지 이미지 refresh 추가
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/res/layout/fragment_mypage.xml
Labels: Fix🔧

#173 [Design] 전반적인 UI 수정
  app/src/main/res/layout/activity_mypage_behavior.xml
  app/src/main/res/layout/activity_mypage_daily.xml
  app/src/main/res/layout/activity_mypage_hospital.xml
  app/src/main/res/layout/activity_mypage_other_users.xml
  app/src/main/res/layout/activity_mypage_pet.xml
  app/src/main/res/layout/activity_setting.xml
Labels: Design🎨

#174 [FIX] 좋아요 목록 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
Labels: Fix🔧

#176 [Design] 공지사항, 회원탈퇴 수정, Mypage 좋아요 목록 ellipsize/maxLines 추가
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/fragment_resignation.xml
  app/src/main/res/layout/item_mypage_like_list.xml
Labels: Design🎨

#177 [FIX] 마이 피드 이미지 수정 즉각 반영
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageOtherUsers.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageDaily.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
Labels: Fix🔧

#178 [FEAT] 다크모드 제한
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MainActivity.kt
Labels: Feature⚙️

#179 [feature]/homerefresh
  app/src/main/java/com/kittyandpuppy/withallmyanimal/SplashActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
Labels: Feature⚙️

#180 [FEAT] : 홈피드 검색 완료시 키보드 내리기
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
Labels: Feature⚙️

#181 [feature] homerefresh
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/LoginAddItemFragment.kt
Labels: Feature⚙️

#182 [feature]/homerefresh
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageOtherUsers.kt
Labels: BugFix🐞

#183 [REFACTORING] 프로필 이미지 경로 변경
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MainActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageOtherUsers.kt
Labels: Refactor♻️

#184 [FIX] : 홈피드 ->디테일엑티비티 두개 뜨는 문제 해결
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
Labels: BugFix🐞

#185 [FIX] StartForResult 오류 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
Labels: BugFix🐞

#186 [FIX] IndexOutOfBoundsException 오류 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
Labels: BugFix🐞

#187 [feature]/homerefresh
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
Labels: Fix🔧

#188 [FIX] 다른 유저가 보는 마이페이지 ActivityResultLauncher
  app/src/main/java/com/kittyandpuppy/withallmyanimal/SplashActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeViewModel.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageOtherUsers.kt
Labels: Fix🔧

#190 [feature]/homerefresh
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
Labels: Feature⚙️

#191 [feature]/homerefresh
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/LoginAddItemFragment.kt
Labels: Fix🔧

#192 [feature]/homerefresh
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/LoginActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/LoginAddItemFragment.kt
  app/src/main/res/layout/fragment_login_add_item.xml
Labels: Fix🔧

#193 [FIX] 병원 일지 수정 시 즉각 업데이트
  app/build.gradle.kts
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/res/layout/activity_mypage_hospital.xml
Labels: Fix🔧

#194 [FIX] MypageFragment 프로필 사진 변경 시 즉시 반영
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/DialogProfileChange.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
Labels: Fix🔧

#195 [feature/homerefresh] 게시글을 최신순으로 정렬
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/Models.kt
Labels: Feature⚙️

#196 [FIX] 유저 프로필 페이지 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageOtherUsers.kt
Labels: Fix🔧

#197 [FIX] 마이피드 - 좋아요 목록 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageOtherUsers.kt
Labels: Fix🔧

#198 [FEAT] HomepageFragment 게시물 랜덤 & 새로고침 시 스크롤 맨 상단으로 고정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
Labels: Feature⚙️

#199 [REFACTORING] 댓글 삭제 기능 경로 수정 & 프로필 사진 변경 경로 변경
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/DialogProfileChange.kt
Labels: Refactor♻️

#200 [FEAT] : RDB에서도 유저정보 삭제되게 변경
  app/src/main/java/com/kittyandpuppy/withallmyanimal/setting/ResignDialogFragment.kt
Labels: Feature⚙️

#201 [FIX] 로그인 실패 시 로그인 실패 토스트 띄우기
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/LoginActivity.kt
Labels: BugFix🐞
