Repository WithAllMyAnimal/KittyAndPuppy, pull requests merged in 2023-10, with the labels that each got.

#8 Design/loginpage
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-12__7_32__Changes_.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-12_오후_7_32_[Changes]/shelved.patch
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/LoginActivity.kt
  app/src/main/res/drawable/cat_sole.png
  app/src/main/res/font/ari.ttf
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
Labels: Design🎨

#10 [DESIGN] : 🎨(sd): 공지사항 페이지 생성
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/background_roundcorner.xml
  app/src/main/res/drawable/image_vaccination.png
  app/src/main/res/layout/activity_notice.xml
Labels: Design🎨

#11 Design/homefragment
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-13__11_50__Changes_.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-13_오전_11_50_[Changes]/image_sample.jpg
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-13_오전_11_50_[Changes]/image_tape.png
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-13_오전_11_50_[Changes]/shelved.patch
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/HomeFragment.kt
  app/src/main/res/drawable/detail_circle_shape.xml
  app/src/main/res/drawable/image_chat.xml
  app/src/main/res/drawable/image_sample.jpg
  app/src/main/res/drawable/image_tape.png
  app/src/main/res/layout/activity_home_hospital.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/values/spinnerItem.xml
  app/src/main/res/values/strings.xml
Labels: Design🎨

#13 [Design]Mypage 일지 작성 템플릿(병원, 펫용품, 이상행동)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MypagePet.kt
  app/src/main/res/drawable/image_save.png
  app/src/main/res/drawable/mypage_btn_tag_background.xml
  app/src/main/res/drawable/mypage_diary_background.xml
  app/src/main/res/drawable/mypage_diary_edittext.xml
  app/src/main/res/drawable/mypage_diary_picture_background.xml
  app/src/main/res/layout/activity_mypage_behavior.xml
  app/src/main/res/layout/activity_mypage_hospital.xml
  app/src/main/res/layout/activity_mypage_pet.xml
  app/src/main/res/values/colors.xml
Labels: Design🎨

#15 [Design]MypageDiary UI 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MypageDaily.kt
  app/src/main/res/layout/activity_mypage_behavior.xml
  app/src/main/res/layout/activity_mypage_daily.xml
  app/src/main/res/layout/activity_mypage_hospital.xml
  app/src/main/res/layout/activity_mypage_pet.xml
Labels: Design🎨

#18 [DESIGN] : 🎨(sd): 설정 페이지 생성
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MainActivity.kt
  app/src/main/res/drawable/switch_thumb.xml
  app/src/main/res/drawable/switch_thumb_selector.xml
  app/src/main/res/drawable/switch_track_off.xml
  app/src/main/res/drawable/switch_track_on.xml
  app/src/main/res/drawable/switch_track_selector.xml
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/values/colors.xml
Labels: Design🎨

#21 [DESIGN] 반려견/반려묘 등록창 UI추가
  app/build.gradle.kts
  app/src/main/res/drawable/baseline_keyboard_arrow_down.xml
  app/src/main/res/drawable/btn_signup.xml
  app/src/main/res/drawable/custom_spinner_background.xml
  app/src/main/res/drawable/edit_text_smple.xml
  app/src/main/res/layout/activity_dog_and_cat_add.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/style.xml
Labels: Design🎨

#22 [Design] 일지 상세 페이지 - 펫 용품
  app/src/main/res/layout/activity_detail_pet.xml
Labels: Design🎨

#24 [Design] 일지 상세 페이지 - 이상행동 UI
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/DetailBehaviorActivity.kt
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/layout/activity_detail_pet.xml
Labels: Design🎨

#28 [DESIGN] : 🎨(sd): 마이페이지 profilechange 생성
  app/src/main/java/com/kittyandpuppy/withallmyanimal/SettingActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/SettingLogoutFragment.kt
  app/src/main/res/layout/fragment_mypage_profilechange.xml
  app/src/main/res/layout/fragment_setting_logout.xml
  app/src/main/res/layout/fragment_setting_passworddialog.xml
Labels: Design🎨

#29 [Design]Mypage
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MypageOtherUsersFragment.kt
  app/src/main/res/drawable/edit_text_sample.xml
  app/src/main/res/drawable/image_mypage_diary_button.xml
  app/src/main/res/drawable/img_mypage_setting.xml
  app/src/main/res/drawable/mypage_change_button.xml
  app/src/main/res/drawable/mypage_profile_shape.xml
  app/src/main/res/layout/activity_dog_and_cat_add.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_mypage_behavior.xml
  app/src/main/res/layout/activity_mypage_daily.xml
  app/src/main/res/layout/activity_mypage_hospital.xml
  app/src/main/res/layout/activity_mypage_pet.xml
  app/src/main/res/layout/fragment_find_password.xml
  app/src/main/res/layout/fragment_login_add_item.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_mypage_other_users.xml
  app/src/main/res/layout/item_mypage_like_list.xml
  app/src/main/res/layout/item_mypage_list.xml
Labels: Design🎨

#31 [Design]Mypage UI변경
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MypageOtherUsers.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MypageOtherUsersFragment.kt
  app/src/main/res/drawable/mypage_btn_blue_shape.xml
  app/src/main/res/drawable/mypage_btn_selector.xml
  app/src/main/res/layout/activity_mypage_other_users.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: Design🎨

#32 [Feat] firebase 설치
  app/build.gradle.kts
  app/google-services.json
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home.xml
  build.gradle.kts
Labels: Feature⚙️

#34 [DESIGN] : 🎨 마이페이지 profilechange UI수정
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/fragment_mypage_profilechange.xml
  app/src/main/res/layout/fragment_setting_logout.xml
  app/src/main/res/layout/fragment_setting_passworddialog.xml
Labels: Design🎨

#35 [FIX] 일부 디자인 수정 및 실행되지않는 오류 수정
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/DetailCommentsFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/DogAndCatAddActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/FindPasswordFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/LoginActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/LoginAddItemFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MainActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MypageDaily.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MypageOtherUsers.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MypagePet.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/SettingActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/SettingLogoutFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/layout/activity_detail_daily.xml
  app/src/main/res/layout/activity_dog_and_cat_add.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_find_password.xml
  app/src/main/res/layout/fragment_login_add_item.xml
  app/src/main/res/values/colors.xml
Labels: BugFix🐞, Design🎨

#36 [Design] Mypage 템플릿 수정
  app/src/main/res/layout/activity_mypage_behavior.xml
  app/src/main/res/layout/activity_mypage_daily.xml
  app/src/main/res/layout/activity_mypage_hospital.xml
  app/src/main/res/layout/activity_mypage_pet.xml
Labels: Design🎨

#37 [feature] firebase 연동
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/LoginActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/LoginAddItemFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/firebase/FBAuth.kt
  app/src/main/res/drawable/image_delete.xml
  app/src/main/res/drawable/image_edit.xml
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/layout/activity_detail_daily.xml
  app/src/main/res/layout/activity_detail_hospital.xml
  app/src/main/res/layout/activity_detail_pet.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/item_home.xml
Labels: Feature⚙️

#39 [Design]/loginpage
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/FindPasswordFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/LoginAddItemFragment.kt
  app/src/main/res/layout/activity_dog_and_cat_add.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_find_pw.xml
  app/src/main/res/layout/fragment_login_add_item.xml
Labels: Design🎨

#41 [Feature] BottomNavigation
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/LoginActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/main_menu.xml
Labels: Feature⚙️

#43 [Feature] BottomNavigation 수정
  app/src/main/res/layout/activity_main.xml
Labels: BugFix🐞, Feature⚙️

#44 [Feature] BottomNavigation Fragment 연결 오류 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MainActivity.kt
  app/src/main/res/layout/activity_mypage_other_users.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: Feature⚙️, Fix🔧

#47 [Design] BottomNavigation UI 일부 수정
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/main_menu.xml
  app/src/main/res/values/themes.xml
Labels: Design🎨

#48 [Design] BottomNavigation 오류 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MainActivity.kt
  app/src/main/res/anim/fab_anim.xml
  app/src/main/res/anim/hide_fab_anim.xml
  app/src/main/res/drawable/bn_home.xml
  app/src/main/res/drawable/main_behavior.png
  app/src/main/res/drawable/main_daily.png
  app/src/main/res/drawable/main_hospital.png
  app/src/main/res/drawable/main_pet_toy.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fab_layout.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/menu/main_menu.xml
Labels: Design🎨

#49 [Design Fix] 일지 작성 템플릿 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MainActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/res/layout/activity_mypage_behavior.xml
  app/src/main/res/layout/activity_mypage_daily.xml
  app/src/main/res/layout/activity_mypage_hospital.xml
  app/src/main/res/layout/activity_mypage_pet.xml
  app/src/main/res/layout/fab_layout.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/menu/main_menu.xml
Labels: Design🎨

#50 [FEAT] 일지 이미지 db 업로드
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/LoginAddItemFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MainActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/firebase/FBRef.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/firebase/util.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/Models.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageDaily.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
  app/src/main/res/layout/activity_mypage_behavior.xml
  app/src/main/res/layout/activity_mypage_daily.xml
  app/src/main/res/layout/activity_mypage_hospital.xml
  app/src/main/res/layout/activity_mypage_pet.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/spinnerItem.xml
Labels: BugFix🐞, Design🎨, Feature⚙️

#54 [FEAT] : ⚙️(Setting activity 에서 Fragment로 이동 기능 구현): mypage에서 setting…
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/NoticeActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/SettingActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/res/layout/activity_notice.xml
Labels: Feature⚙️

#57 [Feature]/loginpage
  app/build.gradle.kts
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/FindPasswordFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/FindPwFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/LoginActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/LoginAddItemFragment.kt
  app/src/main/res/layout/activity_dog_and_cat_add.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_find_pw.xml
  app/src/main/res/layout/fragment_login_add_item.xml
  build.gradle.kts
Labels: Design🎨, Feature⚙️

#59 [Design] font 변경, textColor 변경, bottomNv selector 추가, menu title 변경, tabIndicatorHeight 변경
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-12_오후_7_32_[Changes]/shelved.patch
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MainActivity.kt
  app/src/main/res/color/bottom_nv_selector_icon.xml
  app/src/main/res/color/bottom_nv_selector_text.xml
  app/src/main/res/drawable/add_image.png
  app/src/main/res/drawable/daily_icon.png
  app/src/main/res/drawable/feed_icon.png
  app/src/main/res/drawable/my_home_icon.png
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/layout/activity_detail_daily.xml
  app/src/main/res/layout/activity_detail_hospital.xml
  app/src/main/res/layout/activity_detail_pet.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_mypage_behavior.xml
  app/src/main/res/layout/activity_mypage_daily.xml
  app/src/main/res/layout/activity_mypage_hospital.xml
  app/src/main/res/layout/activity_mypage_pet.xml
  app/src/main/res/layout/fab_layout.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/menu/main_menu.xml
  app/src/main/res/values/style.xml
Labels: Design🎨

#60 [DESIGN] : 🎨(Setting activity 에서 Fragment로 이동 기능 구현): dialogpage 사이즈 조절
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-12__7_32__Changes_.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/DialogProfileChange.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/SettingLogoutFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/SettingPasswordDialogFragment.kt
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/fragment_dialog_profilechange.xml
  app/src/main/res/layout/fragment_setting_logout.xml
  app/src/main/res/layout/fragment_setting_passworddialog.xml
Labels: Design🎨

#61 [Design] Mypage 생일 앞에 케이크 icon 추가, Mypage tag Button 클릭 시 바뀐 색 고정 & 다른 태그 클릭 시 기존 tag 해제
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/res/drawable/cake_icon.png
  app/src/main/res/drawable/mypage_btn_selector.xml
  app/src/main/res/layout/fragment_detail_comments.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: Design🎨

#63 [FEAT] : ⚙️(다크모드 기능구현, 잉글리쉬모드 스위치 기능구현,로그아웃 기능구현):
  .idea/deploymentTargetDropDown.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-13__11_50__Changes_.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-13__11_58__Changes_.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-13_오전_11_50_[Changes]/image_sample.jpg
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-13_오전_11_50_[Changes]/image_tape.png
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-13_오전_11_50_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-13_오전_11_58_[Changes]/shelved.patch
  app/src/main/java/com/kittyandpuppy/withallmyanimal/SettingActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/SettingLogoutFragment.kt
  app/src/main/res/values-night/color.xml
  app/src/main/res/values-night/themes.xml
Labels: Feature⚙️

#64 [FEAT] : 마이페이지에서 프로필설정 눌렀을때 이동 기능구현
  app/src/main/java/com/kittyandpuppy/withallmyanimal/DialogProfileChange.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/SettingActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/res/layout/fragment_dialog_profilechange.xml
Labels: Feature⚙️

#65 [FEAT] 일지 피드 - db 불러오기 완료
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeModel.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/res/drawable/mypage_btn_blue_shape.xml
  app/src/main/res/drawable/mypage_btn_tag_background.xml
  app/src/main/res/drawable/mypage_diary_background.xml
  app/src/main/res/drawable/mypage_diary_edittext.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_mypage_pet.xml
  app/src/main/res/layout/fab_layout.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home.xml
Labels: Design🎨, Feature⚙️, Fix🔧

#68 [Feature]/loginpage
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/DogAndCatAddActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/LoginActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/LoginAddItemFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/UserInfoModel.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/firebase/FBRef.kt
  app/src/main/res/layout/activity_dog_and_cat_add.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_detail_comments.xml
  app/src/main/res/layout/fragment_dialog_profilechange.xml
  app/src/main/res/layout/fragment_find_pw.xml
  app/src/main/res/layout/fragment_login_add_item.xml
Labels: Design🎨, Feature⚙️, Fix🔧

#69 Feature/loginpage
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/LoginActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: Fix🔧

#70 [FEAT] 일지 상세 페이지 - ID 값 불러오기
  app/src/main/java/com/kittyandpuppy/withallmyanimal/firebase/FBRef.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/res/drawable/image_no_images_found.png
  app/src/main/res/layout/item_home.xml
Labels: Fix🔧

#72 [Design] fix design
  app/src/main/res/anim/fab_anim.xml
  app/src/main/res/anim/hide_fab_anim.xml
  app/src/main/res/drawable/detail_background.xml
  app/src/main/res/drawable/mypage_btn_blue_shape.xml
  app/src/main/res/drawable/mypage_btn_tag_background.xml
  app/src/main/res/drawable/mypage_diary_background.xml
  app/src/main/res/drawable/mypage_diary_edittext.xml
  app/src/main/res/drawable/mypage_profile_shape.xml
  app/src/main/res/drawable/pencil_icon.png
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/layout/activity_detail_daily.xml
  app/src/main/res/layout/activity_detail_hospital.xml
  app/src/main/res/layout/activity_detail_pet.xml
  app/src/main/res/layout/activity_dog_and_cat_add.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_mypage_behavior.xml
  app/src/main/res/layout/activity_mypage_daily.xml
  app/src/main/res/layout/activity_mypage_hospital.xml
  app/src/main/res/layout/activity_mypage_pet.xml
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/fragment_login_add_item.xml
  app/src/main/res/values/colors.xml
Labels: Design🎨

#73 [Design fix] UI 수정
  app/src/main/res/layout/activity_dog_and_cat_add.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/fab_layout.xml
  app/src/main/res/layout/fragment_detail_comments.xml
  app/src/main/res/layout/fragment_dialog_profilechange.xml
  app/src/main/res/layout/fragment_find_pw.xml
  app/src/main/res/layout/fragment_login_add_item.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_setting_logout.xml
  app/src/main/res/layout/fragment_setting_passworddialog.xml
  app/src/main/res/layout/item_comments.xml
Labels: Design🎨

#74 UI/fix design
  app/build.gradle.kts
  app/src/main/res/drawable/background_roundcorner.xml
  app/src/main/res/drawable/btn_signup.xml
  app/src/main/res/drawable/custom_spinner_background.xml
  app/src/main/res/drawable/edit_text_sample.xml
  app/src/main/res/drawable/mypage_btn_selector.xml
  app/src/main/res/drawable/tag_background_white.xml
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/layout/activity_detail_daily.xml
  app/src/main/res/layout/activity_detail_hospital.xml
  app/src/main/res/layout/activity_detail_pet.xml
  app/src/main/res/layout/activity_dog_and_cat_add.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_mypage_behavior.xml
  app/src/main/res/layout/activity_mypage_daily.xml
  app/src/main/res/layout/activity_mypage_hospital.xml
  app/src/main/res/layout/activity_mypage_pet.xml
  app/src/main/res/layout/fab_layout.xml
  app/src/main/res/layout/fragment_detail_comments.xml
  app/src/main/res/layout/fragment_dialog_profilechange.xml
  app/src/main/res/layout/fragment_find_pw.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_login_add_item.xml
  app/src/main/res/layout/fragment_setting_logout.xml
  app/src/main/res/layout/fragment_setting_passworddialog.xml
Labels: Design🎨

#75 [Feature] Tag 기능, Mypage Tag버튼 2번 클릭 시 선택 해제
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MainActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/Models.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageDaily.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
Labels: Feature⚙️

#76 Feature/loginpage
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-13__12_32__Changes_.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-10-13_오후_12_32_[Changes]/shelved.patch
  app/src/main/java/com/kittyandpuppy/withallmyanimal/DialogProfileChange.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/DogAndCatAddActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/FindPwFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/res/layout/activity_dog_and_cat_add.xml
  app/src/main/res/layout/fragment_dialog_profilechange.xml
  app/src/main/res/layout/fragment_login_add_item.xml
Labels: Feature⚙️, Fix🔧

#77 [FIX] DB board 데이터 구조 변경
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/firebase/FBRef.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageModel.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/Models.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageDaily.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
  app/src/main/res/drawable/image_no_images_found.png
  app/src/main/res/drawable/pet_like.png
  app/src/main/res/drawable/pet_unlike.png
Labels: Fix🔧

#79 [FEATURE] MypageFragment - 내가 쓴 일지 목록 불러오기 구현 완료
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeModel.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageModel.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/Models.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageDaily.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
Labels: Feature⚙️

#81 [FEAT] : recyclerview item 클릭시 상세페이지 이동 구현
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/res/layout/item_comment_alarm.xml
Labels: Feature⚙️

#82 [FEAT] 자동로그인 기능 추가
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/LoginActivity.kt
  app/src/main/res/layout/activity_dog_and_cat_add.xml
Labels: Feature⚙️

#84 [Design] UI fix
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/SplashActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/res/drawable/mypage_diary_background.xml
  app/src/main/res/drawable/mypage_diary_picture_background.xml
  app/src/main/res/drawable/mypage_profile_shape.xml
  app/src/main/res/drawable/splash_item.gif
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/layout/item_mypage_like_list.xml
  app/src/main/res/layout/item_mypage_list.xml
Labels: Design🎨

#85 [Design] EditText 위치 변경, item margin 추가, splash Icon 사이즈 조정, view color 변경
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/res/drawable/mypage_diary_background.xml
  app/src/main/res/layout/activity_mypage_hospital.xml
  app/src/main/res/layout/activity_mypage_pet.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/item_mypage_like_list.xml
  app/src/main/res/layout/item_mypage_list.xml
Labels: Design🎨

#86 [FEAT] 상세페이지로 이동 시 data db에서 불러오기 완료
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/Models.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/layout/activity_detail_daily.xml
  app/src/main/res/layout/activity_detail_hospital.xml
  app/src/main/res/layout/activity_detail_pet.xml
Labels: Feature⚙️

#88 [FEAT] 프로필설정창 이미지 추가 기능
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/DogAndCatAddActivity.kt
  app/src/main/res/layout/activity_dog_and_cat_add.xml
Labels: Feature⚙️

#89 [FIX] DetailHospitalActivity, DetailPetActivity db data 불러오기 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
  app/src/main/res/layout/activity_mypage_pet.xml
Labels: BugFix🐞, Fix🔧

#91 [Design] UI 오류 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
  app/src/main/res/layout/activity_dog_and_cat_add.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_mypage_behavior.xml
  app/src/main/res/layout/activity_mypage_daily.xml
  app/src/main/res/layout/activity_mypage_hospital.xml
  app/src/main/res/layout/activity_mypage_pet.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_setting_logout.xml
  app/src/main/res/layout/fragment_setting_passworddialog.xml
  app/src/main/res/layout/item_mypage_like_list.xml
Labels: Design🎨

#92 [FEAT] : DetailBehaviorActivity 기능구현
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
Labels: Feature⚙️

#94 [FIX] 프로필 설정 이미지 추가 기능
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/DialogProfileChange.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/DogAndCatAddActivity.kt
Labels: Fix🔧

#95 [FEAT] : DetailActivity별 back버튼 추가
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
Labels: Feature⚙️

#96 [FEAT] BottomSheetDialogFragment 댓글 창 구현
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/CommentsRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/DetailCommentsFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/layout/activity_detail_daily.xml
  app/src/main/res/layout/activity_detail_hospital.xml
  app/src/main/res/layout/activity_detail_pet.xml
  app/src/main/res/layout/fragment_detail_comments.xml
  app/src/main/res/layout/item_comments.xml
Labels: Feature⚙️

#98 [Feature]/loginpage
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/DogAndCatAddActivity.kt
Labels: Fix🔧

#99 [Design] Notice UI 수정, 일부 UI 수정
  app/src/main/res/drawable/btn_cancel.xml
  app/src/main/res/drawable/notice_background.xml
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/layout/activity_detail_daily.xml
  app/src/main/res/layout/activity_detail_hospital.xml
  app/src/main/res/layout/activity_detail_pet.xml
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/fragment_setting_logout.xml
Labels: Design🎨

#100 [FEAT] 댓글 기능 구현 중
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeModel.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/Models.kt
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/layout/activity_detail_daily.xml
  app/src/main/res/layout/activity_detail_hospital.xml
  app/src/main/res/layout/activity_detail_pet.xml
  app/src/main/res/layout/fragment_comments.xml
Labels: Feature⚙️

#102 [FIX] 프로필 설정 이미지 추가 기능 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/DialogProfileChange.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/DogAndCatAddActivity.kt
  app/src/main/res/layout/fragment_dialog_profilechange.xml
Labels: Fix🔧

#103 [FEAT] 댓글 기능 구현 완료
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/DogAndCatAddActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsModel.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/DialogProfileChange.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageModel.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/setting/NoticeActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/setting/SettingActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/setting/SettingLogoutFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/setting/SettingPasswordDialogFragment.kt
  app/src/main/res/layout/fragment_comments.xml
  app/src/main/res/layout/item_comments.xml
Labels: Feature⚙️

#105 [Feature]/loginpage
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/Models.kt
  app/src/main/res/layout/fragment_comments.xml
Labels: Feature⚙️

#106 [FIX] MypageFragment에서 BottomNavigation 두 번 클릭 시 다운되는 문제
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/DogAndCatAddActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MainActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/util/Constants.kt
  app/src/main/res/drawable/image_profile_edit.xml
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/layout/activity_detail_daily.xml
  app/src/main/res/layout/activity_detail_hospital.xml
  app/src/main/res/layout/activity_detail_pet.xml
  app/src/main/res/layout/activity_mypage_behavior.xml
  app/src/main/res/layout/activity_mypage_daily.xml
  app/src/main/res/layout/activity_mypage_hospital.xml
  app/src/main/res/layout/fragment_dialog_profilechange.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: BugFix🐞, Fix🔧

#107 [feat] 게시글 추가, 삭제 시 홈피드 화면 즉각 반영
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MyPageRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageDaily.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
  app/src/main/res/layout/alarm_delete.xml
Labels: Feature⚙️

#109 [FEAT] 일지피드에서 좋아요와 댓글 실시간으로 숫자 표기되는 기능 추가
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/Models.kt
  build.gradle.kts
Labels: Feature⚙️

#110 [FIX] Mypage bug fix
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MainActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/DialogProfileChange.kt
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/layout/activity_detail_daily.xml
  app/src/main/res/layout/activity_detail_hospital.xml
  app/src/main/res/layout/activity_detail_pet.xml
  app/src/main/res/layout/activity_mypage_daily.xml
  app/src/main/res/layout/activity_mypage_hospital.xml
  app/src/main/res/layout/activity_mypage_pet.xml
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: BugFix🐞, Design🎨, Fix🔧

#111 [FIX] 댓글창 프로필 사진 불러오기 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsRVAdapter.kt
  app/src/main/res/drawable/profile_edit_button_background.xml
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: Fix🔧

#112 [Design] 피드백에 따른 전반적인 UI 수정
  app/src/main/res/drawable/diary_detail_tag.xml
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/layout/activity_detail_daily.xml
  app/src/main/res/layout/activity_detail_hospital.xml
  app/src/main/res/layout/activity_detail_pet.xml
  app/src/main/res/layout/activity_dog_and_cat_add.xml
  app/src/main/res/layout/activity_mypage_behavior.xml
  app/src/main/res/layout/activity_mypage_daily.xml
  app/src/main/res/layout/activity_mypage_hospital.xml
  app/src/main/res/layout/activity_mypage_other_users.xml
  app/src/main/res/layout/activity_mypage_pet.xml
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/alarm_delete.xml
  app/src/main/res/layout/fragment_dialog_profilechange.xml
  app/src/main/res/layout/item_mypage_like_list.xml
  app/src/main/res/values/colors.xml
Labels: Design🎨

#113 [BugFix] 전반적인 오류 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsModel.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/comments/CommentsRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeRVAdapter.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/MypageFragment.kt
Labels: BugFix🐞

#115 [Design] Dialog에서 상태메세지 삭제
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/DogAndCatAddActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/mypage/DialogProfileChange.kt
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/layout/activity_detail_daily.xml
  app/src/main/res/layout/activity_detail_hospital.xml
  app/src/main/res/layout/activity_detail_pet.xml
  app/src/main/res/layout/activity_dog_and_cat_add.xml
  app/src/main/res/layout/fragment_dialog_profilechange.xml
Labels: Design🎨

#116 [DESIGN] 앱아이콘 및 앱 이름 수정
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
Labels: Design🎨

#117 [Design] 댓글 수정
  app/src/main/res/layout/fragment_comments.xml
  app/src/main/res/layout/item_comments.xml
Labels: Design🎨

#118 [FIX] 갤러리 접근 권한 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/DogAndCatAddActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/firebase/util.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageBehavior.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageDaily.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypageHospital.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/write/MypagePet.kt
Labels: BugFix🐞

#120 [Design] 전반적인 UI 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/MainActivity.kt
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/layout/activity_detail_daily.xml
  app/src/main/res/layout/activity_detail_hospital.xml
  app/src/main/res/layout/activity_detail_pet.xml
  app/src/main/res/layout/activity_dog_and_cat_add.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_mypage_behavior.xml
  app/src/main/res/layout/activity_mypage_daily.xml
  app/src/main/res/layout/activity_mypage_hospital.xml
  app/src/main/res/layout/activity_mypage_pet.xml
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/alarm_delete.xml
  app/src/main/res/layout/fragment_dialog_profilechange.xml
  app/src/main/res/layout/fragment_find_pw.xml
  app/src/main/res/layout/fragment_login_add_item.xml
  app/src/main/res/layout/item_comments.xml
  app/src/main/res/layout/item_mypage_like_list.xml
Labels: Design🎨

#121 [FEAT] DetailPage에서 스크린샷 제한
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailDailyActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailHospitalActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailPetActivity.kt
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/layout/activity_detail_daily.xml
  app/src/main/res/layout/alarm_delete.xml
Labels: Feature⚙️

#122 [FIX] 스피너 연결 수정
  app/src/main/java/com/kittyandpuppy/withallmyanimal/LoginPage/DogAndCatAddActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/detail/DetailBehaviorActivity.kt
  app/src/main/java/com/kittyandpuppy/withallmyanimal/home/HomeFragment.kt
  app/src/main/res/layout/activity_detail_behavior.xml
  app/src/main/res/values/spinnerItem.xml
Labels: Fix🔧

#123 [DESIGN] : 🎨(다크모드 기능삭제, 잉글리쉬모드 스위치 기능삭제 SettingActivity디자인 변경)
  app/src/main/java/com/kittyandpuppy/withallmyanimal/setting/SettingActivity.kt
  app/src/main/res/layout/activity_setting.xml
Labels: Design🎨, Feature⚙️
